manager/urls.py
from django.urls import path
from manager import views

app_name = "manager"


urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("unauthorized_access/", views.unauthorized_access, name="unauthorized_access"),
    
    # design_category
    path("design_category/list/", views.design_category_list, name="design_category_list"),
    path("design_category/add/", views.design_category_add, name="design_category_add"),
    path("design_category/edit/<int:id>/", views.design_category_edit, name="design_category_edit"),
    path("design_category/delete/<int:id>/", views.design_category_delete, name="design_category_delete"),

    # design_category
    path("product/list/", views.product_list, name="product_list"),
    path("product/add/", views.product_add, name="product_add"),
    path("product/edit/<int:id>/", views.product_edit, name="product_edit"),
    path("product/delete/<int:id>/", views.product_delete, name="product_delete"),


    path('services/', views.service_list, name='service_list'),
    path('services/add/', views.service_add, name='service_add'),
    path('services/edit/<int:id>/', views.service_edit, name='service_edit'),
    path('services/delete/<int:id>/', views.service_delete, name='service_delete'),

    
    path('product-image/', views.product_image_list, name='product_image_list'),
    path('product_image/add/', views.product_image_add, name='product_image_add'),
    path('product_image/edit/<int:id>/', views.product_image_edit, name='product_image_edit'),
    path('product_image/delete/<int:id>/', views.product_image_delete, name='product_image_delete'),

    path('testimonials/', views.testimonial_list, name='testimonial_list'),
    path('testimonials/add/', views.testimonial_add, name='testimonial_add'),
    path('testimonials/edit/<int:id>/', views.testimonial_edit, name='testimonial_edit'),
    path('testimonials/delete/<int:id>/', views.testimonial_delete, name='testimonial_delete'),
]

web/urls.py
from django.urls import path
from web import views

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path('single-product-view/<int:id>/', views.single_product_view, name='single_product_view'),
    path('service-detail/<int:id>/', views.service_detail, name='service_detail'),
    path('services/', views.services, name='services'),
    path('gallery/', views.gallery, name='gallery'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('testimonials/', views.testimonials, name='testimonials'),
    path('contact/', views.contact, name='contact'),
    path('send_message/', views.send_message, name='send_message'),
    path('thanks/', views.thanks, name='thanks'),
    path('quiz/', views.quiz, name='quiz'),
    path('product/', views.product, name='product'),
    path('faqs/', views.faqs, name='faqs'),
    path('blog/', views.blog, name='blog'),
    path('careers/', views.careers, name='careers'),
    path('about_us/', views.about_us, name='about_us'),
    path('r/', views.redi, name='redi'),
    path('appointment_booking/', views.appointment_booking, name='appointment_booking'),


]

zbpro/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ("web.urls", namespace="web")),
    path('manager/', include ("manager.urls", namespace="manager")),
]

if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

manager/models.py
from django.db import models

# Create your models here.

manager/forms.py
from django import forms
from web.models import *
from product.models import *
from web.models import *




class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category  # Correct 'models' to 'model'
        fields = ['name', 'image']  # Ensure this is a list or tuple

        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control", "placeholder": "Category name"}),
            "image": forms.FileInput(attrs={"class": "form-control"}),
        }




class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'rating', 'time', 'discount', 'category']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Product Name'}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Description'}),
            'rating': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Rating (e.g., 4.5)'}),
            'time': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Preparation Time'}),
            'discount': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Discount (%)'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
        }





class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ['name', 'description', 'content', 'price', 'duration', 'image']
        
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control", "placeholder": "Service name"}),
            "description": forms.Textarea(attrs={"class": "form-control", "placeholder": "Short description", "rows": 3}),
            "content": forms.Textarea(attrs={"class": "form-control", "placeholder": "Detailed content", "rows": 5}),
            "price": forms.NumberInput(attrs={"class": "form-control", "placeholder": "Service price"}),
            "duration": forms.TextInput(attrs={"class": "form-control", "placeholder": "Duration (e.g., 1 day, 2 hours)"}),
            "image": forms.FileInput(attrs={"class": "form-control"}),
        }



class ProductImageForm(forms.ModelForm):
    class Meta:
        model = ProductImage
        fields = ['product', 'name', 'image']
        widgets = {
            "product": forms.Select(attrs={"class": "form-control"}),
            "name": forms.TextInput(attrs={"class": "form-control", "placeholder": "Image name"}),
            "image": forms.FileInput(attrs={"class": "form-control"}),
        }



class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = ['client_name', 'client_role', 'testimonial_text']

        widgets = {
            "client_name": forms.TextInput(attrs={"class": "form-control", "placeholder": "Client's Name"}),
            "client_role": forms.TextInput(attrs={"class": "form-control", "placeholder": "Client's Role"}),
            "testimonial_text": forms.Textarea(attrs={"class": "form-control", "placeholder": "Testimonial Message", "rows": 4}),
        }

manager/views.py
from main.decorators import allow_manager

from main.functions import generate_form_errors

from main.decorators import allow_manager

from main.functions import generate_form_errors


# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect, reverse

from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout

from django.contrib.auth.decorators import login_required
from product.models import *


from web.models import *


from django.contrib.auth import logout as auth_logout

from django.contrib import messages
from .forms import *
 # Ensure only logged-in users can access the index view


# @login_required(login_url='manager:login')
# @allow_manager
def index(request):
    
    return render(request, 'manager/index.html')

def unauthorized_access(request):
    
    return render(request, 'manager/unauthorized_access.html')


def login(request):
#     if request.method == 'POST':
#         form = ManagerLoginForm(request.POST)
#         if form.is_valid():
#             email = form.cleaned_data['email']
#             password = form.cleaned_data['password']
#             user = authenticate(request, email=email, password=password)
#             if user is not None:
#                 if user.is_manager:  # Check if the user has manager rights
#                     auth_login(request, user)  # Use Django's login function with alias
#                     return redirect('manager:index')
#                 else:
#                     messages.error(request, 'Unauthorized access.')
#                     return HttpResponse("Unauthorized", status=401)
#             else:
#                 messages.error(request, 'Invalid email or password.')
#         else:
#             messages.error(request, 'Invalid form data.') 
#     else:
#         form = ManagerLoginForm()

    return render(request, 'manager/login.html')




def logout_view(request):
    auth_logout(request)
    return redirect('manager:login')  # Redirect to the login page


def register(request):
    
    return render(request, 'manager/register.html')

# store_category

def design_category_list(request):
    instances = Category.objects.all()

    context = {
            "instances": instances,
            
    }
    return render(request, 'manager/design_category_list.html', context=context)


def design_category_add(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('manager:design_category_list'))
    else:
        form = CategoryForm()

    return render(request, 'manager/forms/design_category_add_form.html', {'form': form})



def design_category_edit(request, id):
    design_category = get_object_or_404(Category, id=id)

    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES, instance=design_category)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('manager:design_category_list'))
    else:
        form = CategoryForm(instance=design_category)

    return render(request, 'manager/forms/design_category_add_form.html', {'form': form, 'is_edit': True, 'design_category': design_category})



# Delete View
def design_category_delete(request, id):
    instance = get_object_or_404(Category, id=id)
    model = instance.__class__.__name__
    if request.method == 'POST':
        instance.delete()
        return redirect('manager:testimonial_list')
    
    
    context = {
        'instance': instance,
        'model': model,
    }
    
    return render(request, 'manager/confirm_delete.html', context=context)


# Product

def product_list(request):
    instances = Product.objects.all()

    context = {
            "instances": instances,
    }
    return render(request, 'manager/product_list.html', context=context)


def product_add(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('manager:product_list'))
    else:
        form = ProductForm()

    return render(request, 'manager/forms/product_add.html', {'form': form})



def product_edit(request, id):
    instance = get_object_or_404(Product, id=id)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=Product)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('manager:product_list'))
    else:
        form = ProductForm(instance=Product)

    return render(request, 'manager/forms/product_add.html', {'form': form, 'is_edit': True, 'instance': instance})



# # Edit View
# def product_edit(request, id):
#     instance = get_object_or_404(Product, id=id)
#     if request.method == 'POST':
#         form = Product(request.POST, request.FILES, instance=instance)
#         if form.is_valid():
#             form.save()
#             return redirect('manager:product_list')
#     else:
#         form = ProductForm(instance=instance)
#     return render(request, 'manager/forms/product_add.html', {'form': form, 'instance': instance})


def product_delete(request, id):
    instance = get_object_or_404(Product, id=id)
    model = instance.__class__.__name__
    if request.method == 'POST':
        instance.delete()
        return redirect('manager:product_image_list')
    
    context = {
        'instance': instance,
        'model': model,
    }

    return render(request, 'manager/confirm_delete.html', context=context)




# List View service
def service_list(request):
    instances = Service.objects.all()
    return render(request, 'manager/service_list.html', {'instances': instances})

# Add View
def service_add(request):
    if request.method == 'POST':
        form = ServiceForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('manager:service_list')
    else:
        form = ServiceForm()
    return render(request, 'manager/forms/service_add.html', {'form': form})

# Edit View
def service_edit(request, id):
    instance = get_object_or_404(Service, id=id)
    if request.method == 'POST':
        form = ServiceForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('manager:service_list')
    else:
        form = ServiceForm(instance=instance)
    return render(request, 'manager/forms/service_add.html', {'form': form, 'instance': instance})

# Delete View
def service_delete(request, id):
    instance = get_object_or_404(Service, id=id)
    model = instance.__class__.__name__
    if request.method == 'POST':
        instance.delete()
        return redirect('manager:service_list')
    
    context = {
        'instance': instance,
        'model': model,
    }
    return render(request, 'manager/confirm_delete.html', context=context)


# photos

def product_image_list(request):
    instances = ProductImage.objects.all()
    return render(request, 'manager/product_image_list.html', {'instances': instances})


def product_image_add(request):
    if request.method == 'POST':
        form = ProductImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('manager:product_image_list')
    else:
        form = ProductImageForm()
    return render(request, 'manager/forms/product_image_add.html', {'form': form})

def product_image_edit(request, id):
    instance = get_object_or_404(ProductImage, id=id)
    if request.method == 'POST':
        form = ProductImageForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('manager:product_image_list')
    else:
        form = ProductImageForm(instance=instance)
    return render(request, 'manager/product_image_list.html', {'form': form, 'instance': instance})

def product_image_delete(request, id):
    instance = get_object_or_404(ProductImage, id=id)
    model = instance.__class__.__name__
    if request.method == 'POST':
        instance.delete()
        return redirect('manager:product_image_list')
    
    
    context = {
        'instance': instance,
        'model': model,
    }
    return render(request, 'manager/confirm_delete.html', context=context)




# tersjhdmf

# List View
def testimonial_list(request):
    instances = Testimonial.objects.all()
    return render(request, 'manager/testimonial_list.html', {'instances': instances})

# Add View
def testimonial_add(request):
    if request.method == 'POST':
        form = TestimonialForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('manager:testimonial_list')
    else:
        form = TestimonialForm()
    return render(request, 'manager/forms/testimonial_add.html', {'form': form})

# Edit View
def testimonial_edit(request, id):
    instance = get_object_or_404(Testimonial, id=id)
    if request.method == 'POST':
        form = TestimonialForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('manager:testimonial_list')
    else:
        form = TestimonialForm(instance=instance)
    return render(request, 'manager/forms/testimonial_add.html', {'form': form, 'instance': instance})

# Delete View
def testimonial_delete(request, id):
    instance = get_object_or_404(Testimonial, id=id)
    model = instance.__class__.__name__
    if request.method == 'POST':
        instance.delete()
        return redirect('manager:testimonial_list')
    
    
    context = {
        'instance': instance,
        'model': model,
    }
    
    return render(request, 'manager/confirm_delete.html', context=context)

templates/manager/confirm_delete.html
{% extends 'base/manager-base.html' %} 
{% load static %} 
{% block container %}

<!-- Centered Popup Container -->
<div class="d-flex justify-content-center align-items-center min-vh-100">
    <div class="card shadow-lg border-0" style="max-width: 450px; border-radius: 10px;">
        <div class="card-body p-4">
            <h4 class="card-title text-danger mb-3 text-center">Delete Confirmation</h4>
            <p class="text-center">Are you sure you want to delete this <strong>{{ instance }}</strong>?</p>
            
            {% if instance.name %}
            <div class="mb-3 text-center">
                <strong>Service Name:</strong> {{ instance.name }}
            </div>
            {% endif %}

            {% if instance.description %}
            <p class="text-center"><strong>Description:</strong> {{ instance.description }}</p>
            {% endif %}

            {% if instance.client_name %}
            <p class="text-center"><strong>Client Name:</strong> {{ instance.client_name }}</p>
            {% endif %}

            {% if instance.client_role %}
            <p class="text-center"><strong>Client Role:</strong> {{ instance.client_role }}</p>
            {% endif %}

            {% if instance.testimonial_text %}
            <p class="text-center"><strong>Testimonial:</strong> {{ instance.testimonial_text }}</p>
            {% endif %}

            {% if instance.email %}
            <p class="text-center"><strong>Email:</strong> {{ instance.email }}</p>
            {% endif %}

            {% if instance.phone %}
            <p class="text-center"><strong>Phone:</strong> {{ instance.phone }}</p>
            {% endif %}

            {% if instance.message %}
            <p class="text-center"><strong>Message:</strong> {{ instance.message }}</p>
            {% endif %}

            {% if instance.preferred_date %}
            <p class="text-center"><strong>Preferred Date:</strong> {{ instance.preferred_date }}</p>
            {% endif %}

            {% if instance.preferred_time %}
            <p class="text-center"><strong>Preferred Time:</strong> {{ instance.preferred_time }}</p>
            {% endif %}

            {% if instance.image %}
            <div class="text-center mb-3">
                <img src="{{ instance.image.url }}" class="rounded border" style="width: 120px; height: 120px; object-fit: cover;" alt="Service Image">
            </div>
            {% endif %}

            <!-- Image Styling for Additional Images -->
            {% if instance.images.first %}
            
            <div class="text-center mb-3">
                <img src="{{ instance.images.first.image.url }}" class="rounded border" style="margin: auto; width: 120px; height: 120px; object-fit: cover;" alt="Service Image">
            </div>
            {% endif %}

            
            <!-- Confirm and Cancel Buttons -->
            <form method="POST" class="d-flex justify-content-center">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger mr-2">Confirm Delete</button>
                {% if model == "Service" %}
                    <a href="{% url 'manager:service_list' %}" class="btn btn-secondary">Cancel</a>
                {% elif model == "Product" %}
                    <a href="{% url 'manager:product_list' %}" class="btn btn-secondary">Cancel</a>
                {% elif model == "Testimonial" %}
                    <a href="{% url 'manager:testimonial_list' %}" class="btn btn-secondary">Cancel</a>
                {% elif model == "Category" %}
                    <a href="{% url 'manager:design_category_list' %}" class="btn btn-secondary">Cancel</a>
                {% elif model == "ProductImage" %}
                    <a href="{% url 'manager:product_image_list' %}" class="btn btn-secondary">Cancel</a>
                {% elif model == "Appointment" %}
                    <a href="{% url 'manager:appointment_list' %}" class="btn btn-secondary">Cancel</a>
                {% elif model == "Appointment" %}
                    <a href="{% url 'manager:appointment_list' %}" class="btn btn-secondary">Cancel</a>
                {% endif %}
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/manager/design_category_list.html
{% extends 'base/manager-base.html' %} 
{% load static %} 
{% block container %}

<!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->

    
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        
    {% include 'include/manager-nav.html' %}

        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Home</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Category Table</h4>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Name</th>
                                                <th>Image</th>
                                                <th>Edit</th>
                                                <th>Delet</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for instance in instances %}
                                            <tr>
                                                <td>{{ instance.id }}</td>
                                                <td>{{ instance.name }}</td>
                                                <td><img src="{{ instance.image.url }}" class="" alt="" style="width: 60px; height: 60px;"></td>
                                                <td><a href="{% url 'manager:design_category_edit' id=instance.id %}"><button type="button" class="btn mb-1 btn-outline-primary">Edit</button></a></td>
                                                <td><a href="{% url 'manager:design_category_delete' id=instance.id %}"><button type="button" class="btn mb-1 btn-outline-danger">Delete</button></a></td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th>ID</th>
                                                <th>Name</th>
                                                <th>Image</th>
                                                <th>Edit</th>
                                                <th>Delet</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        
        
        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2018</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->
    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    {% endblock %}

templates/manager/message_list.html
{% extends 'base/manager-base.html' %} 
{% load static %} 
{% block container %}

<!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->

    
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        
    {% include 'include/manager-nav.html' %}

        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Home</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Category Table</h4>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Service Name</th>
                                                <th>Description</th>
                                                <th>Price</th>
                                                <th>Duration</th>
                                                <th>Image</th>
                                                <th>Edit</th>
                                                <th>Delete</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for instance in instances %}
                                            <tr>
                                                <td>{{ instance.id }}</td>
                                                <td>{{ instance.name }}</td>
                                                <td>{{ instance.description }}</td>
                                                <td>${{ instance.price }}</td>
                                                <td>{{ instance.duration }}</td>
                                                <td>
                                                    <img src="{{ instance.image.url }}" alt="{{ instance.name }}" style="width: 60px;" />
                                                </td>
                                                <td>
                                                    <a href="{% url 'manager:service_edit' id=instance.id %}">
                                                        <button type="button" class="btn mb-1 btn-outline-primary">Edit</button>
                                                    </a>
                                                </td>
                                                <td>
                                                    <a href="{% url 'manager:service_delete' id=instance.id %}">
                                                        <button type="button" class="btn mb-1 btn-outline-danger">Delete</button>
                                                    </a>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>                                    
                                                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        
        
        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2018</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->
    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    {% endblock %}